### ISSUE TITLE
Create Boombox 7 Contract.

### ISSUE THREAD

**Issue by dantrevino** [boomcrypto/boom-contracts#9]
- set max mint at 10000 in addition to time limit
- mint time limit: #720350

**Comment by friedger** [comment]
NFT contract: SP1QK1AZ24R132C0D84EEQ8Y2JDHARDR58R72E1ZW.boomboxes-cycle-26

Deployed with id 4
https://explorer.stacks.co/txid/0xe625695af0f0059e5189fd9dcb396f32981c43e13f658527a6d5bd981b1feea1?chain=mainnet
